FROM oven/bun:latest

WORKDIR /src/app

COPY  ./packages ./packages
COPY package.json bun.lockb turbo.json ./
COPY ./apps/backend ./apps/backend

RUN bun install
COPY . .


RUN bun run db:generate

EXPOSE 3000

CMD [ "bun","run","start:backend" ]