FROM oven/bun:1

WORKDIR /src/app
COPY ./packages ./packages 
COPY ./package.json ./package.json
COPY ./bun.lockb ./bun.lockb
COPY ./turbo.json ./turbo.json

RUN bun install

COPY ./apps/web ./apps/web

RUN bun run db:generate
RUN bun run build

EXPOSE 3002

CMD [ "bun","run","start:frontend" ]