FROM oven/bun:latest

WORKDIR /src/app
ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}
COPY ./packages ./packages 
COPY package.json bun.lockb turbo.json ./
COPY ./apps/web ./apps/web

RUN bun install


RUN bun run db:generate

RUN bun run build:frontend

EXPOSE 3002

CMD [ "bun","run","start:frontend" ]