name: Continuous Deployment Backend
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the codebase in ubuntu machine
        uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Docker/Dockerfile.backend
          push: true
          tags: docker_with_cicd_practice/backend:${{github.sha}}
